name: Build Python iOS (arm64)

on:
  push:
    branches:
      - run-actions
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

env:
  PYTHON_VERSION: "3.14"

jobs:
  build-python-ios-arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: python/cpython
          ref: ${{ env.PYTHON_VERSION }}

      - name: Install autotools dependencies
        run: |
          brew install autoconf automake libtool

      - name: List brew bin
        run: ls /opt/homebrew/bin

      - name: Build host macOS Python
        run: |
          ./configure --prefix=$(pwd)/cross-build/macOS
          make -j2 all
          make install
        shell: bash

      - name: Set environment path for iOS
        run: |
          export IOS_SDK=$(xcrun --sdk iphoneos --show-sdk-path)
          export CC=$(xcrun -sdk iphoneos -f clang)
          export CFLAGS="-isysroot $IOS_SDK -arch arm64 -mios-version-min=12.0"
          export LDFLAGS="$CFLAGS"
          export TARGET_DIR=$(pwd)/cross-build/iphoneos.arm64
          mkdir -p deps_build
          echo "IOS_SDK=$IOS_SDK" >> $GITHUB_ENV
          echo "CC=$CC" >> $GITHUB_ENV
          echo "CFLAGS=$CFLAGS" >> $GITHUB_ENV
          echo "LDFLAGS=$LDFLAGS" >> $GITHUB_ENV
          echo "TARGET_DIR=$TARGET_DIR" >> $GITHUB_ENV
          mkdir -p deps_build
        shell: bash

      - name: Configure iOS dependencies
        shell: bash
        run: |
          mkdir -p $TARGET_DIR

          cd deps_build

          git clone https://github.com/libffi/libffi.git
          cd libffi
          git checkout v3.5.1

          ./autogen.sh

          ./configure \
            --host=arm-apple-darwin \
            --prefix=$TARGET_DIR/libffi \
            --disable-shared \
            --enable-static \
            --disable-dependency-tracking \
            --disable-docs \
            CC="$CC" \
            CFLAGS="$CFLAGS"

          make -j2
          make install

          cd ..

          curl -LO https://tukaani.org/xz/xz-5.2.5.tar.gz
          tar -xf xz-5.2.5.tar.gz
          cd xz-5.2.5

          ./configure \
            --host=arm-apple-darwin \
            --prefix=$TARGET_DIR/xz \
            --disable-shared \
            --enable-static \
            CC="$CC" \
            CFLAGS="$CFLAGS"

          make -j2
          make install

          cd ..

          curl -LO https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz
          tar -xf bzip2-1.0.8.tar.gz
          cd bzip2-1.0.8

          make clean

          make CC="$CC" CFLAGS="$CFLAGS -fPIC" -j2 libbz2.a bzip2 bzip2recover

          make install PREFIX=$TARGET_DIR/bzip2

          cd ..

          curl -LO https://www.openssl.org/source/openssl-1.1.1w.tar.gz
          tar -xf openssl-1.1.1w.tar.gz
          cd openssl-1.1.1w

          ./Configure ios64-cross no-shared no-dso \
            --prefix=$TARGET_DIR/openssl \
            CC="$CC" \
            CFLAGS="$CFLAGS"

          make -j2
          make install_sw

      - name: Configure Python for iOS arm64
        run: |
          export SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)
          export CC=$(xcrun --sdk iphoneos --find clang)
          export CPP="$CC -E"
          export CFLAGS="-isysroot $SDKROOT -arch arm64 -mios-version-min=12.0 -fPIC"
          export LDFLAGS="$CFLAGS"

          ./configure \
            LIBLZMA_CFLAGS="-I$(pwd)/cross-build/iphoneos.arm64/xz/include -I$(pwd)/cross-build/iphoneos.arm64/xz/include/lzma" \
            LIBLZMA_LIBS="-L$(pwd)/cross-build/iphoneos.arm64/xz/lib -llzma" \
            BZIP2_CFLAGS="-I$(pwd)/cross-build/iphoneos.arm64/bzip2/include" \
            BZIP2_LIBS="-L$(pwd)/cross-build/iphoneos.arm64/bzip2/lib -lbz2" \
            LIBFFI_CFLAGS="-I$(pwd)/cross-build/iphoneos.arm64/libffi/include" \
            LIBFFI_LIBS="-L$(pwd)/cross-build/iphoneos.arm64/libffi/lib -lffi" \
            --with-openssl="$(pwd)/cross-build/iphoneos.arm64/openssl" \
            --host=arm64-apple-ios12.0 \
            --build=arm64-apple-darwin \
            --with-build-python="$(pwd)/cross-build/macOS/bin/python${{ env.PYTHON_VERSION }}" \
            --enable-framework \
            CPP="$CPP"
        shell: bash

      - name: Build Python for iOS arm64
        run: |
          make -j2 all
        shell: bash

      - name: Install Python for iOS arm64
        run: |
          make install
        shell: bash

      - name: Upload Python iOS arm64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-${{ env.PYTHON_VERSION }}-ios-arm64
          path: cross-build/iphoneos.arm64
