name: Build Python MacOS (ARM)
on:
  push:
    branches:
      - run-actions
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write

env:
  PYTHON_VERSION: 3.10.18

jobs:
  configure-build-and-package-python-macos-arm:
    runs-on: macos-latest
    steps:
      - name: Download python source
        run: |
          curl -L -# -o Python-${{ env.PYTHON_VERSION }}.tgz \
            https://www.python.org/ftp/python/${{ env.PYTHON_VERSION }}/Python-${{ env.PYTHON_VERSION }}.tgz
        shell: bash

      - name: Extract tar.gz
        run: |
          tar -xf Python-${{ env.PYTHON_VERSION }}.tgz
          mv Python-${{ env.PYTHON_VERSION }}/* .
        shell: bash

      - name: Configure python
        run: |
          ./configure --prefix=/python-${{ env.PYTHON_VERSION }}-macos-arm --enable-optimizations
        shell: bash

      - name: Build python
        run: |
          make -j2
        shell: bash

      - name: Install python
        run: |
          sudo make install
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-${{ env.PYTHON_VERSION }}-macos-arm
          path: /python-${{ env.PYTHON_VERSION }}-macos-arm