name: Build Python MacOS (ARM)

on:
  push:
    branches:
      - run-actions
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

env:
  PYTHON_VERSION: 3.13.5

jobs:
  configure-build-and-package-python-macos-arm:
    runs-on: macos-latest
    steps:
      - name: Download python source
        run: |
          curl -L -# -o Python-${{ env.PYTHON_VERSION }}.tgz \
            https://www.python.org/ftp/python/${{ env.PYTHON_VERSION }}/Python-${{ env.PYTHON_VERSION }}.tgz
        shell: bash

      - name: Extract tar.gz
        run: |
          tar -xf Python-${{ env.PYTHON_VERSION }}.tgz
          mv Python-${{ env.PYTHON_VERSION }}/* .
        shell: bash

      - name: Configure python
        run: |
          ./configure --prefix=$GITHUB_WORKSPACE/python-${{ env.PYTHON_VERSION }}-macos-arm --enable-shared --enable-optimizations
        shell: bash

      - name: Build python
        run: |
          make -j2
        shell: bash

      - name: Install python
        run: |
          sudo make install
        shell: bash

      - name: Patch install names for relocatable build
        run: |
          BIN="$GITHUB_WORKSPACE/python-${{ env.PYTHON_VERSION }}-macos-arm/bin/python${{ env.PYTHON_SHORT_VERSION }}"
          DYLIB="$GITHUB_WORKSPACE/python-${{ env.PYTHON_VERSION }}-macos-arm/lib/libpython${{ env.PYTHON_SHORT_VERSION }}.dylib"

          echo "Before patch:"
          otool -L "$BIN"

          # Change reference to use relative @executable_path
          install_name_tool -change "$DYLIB" "@executable_path/../lib/libpython${{ env.PYTHON_SHORT_VERSION }}.dylib" "$BIN"

          # Change dylib's own install name so it's linkable
          install_name_tool -id "@rpath/libpython${{ env.PYTHON_SHORT_VERSION }}.dylib" "$DYLIB"

          echo "After patch:"
          otool -L "$BIN"

          # Sanity check
          "$BIN" --version
        shell: bash
      
      - name: tar.gz files
        run: |
          cd python-${{ env.PYTHON_VERSION }}-macos-arm
          tar -cvzf ../python-${{ env.PYTHON_VERSION }}-macos-arm.tar.gz *

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-${{ env.PYTHON_VERSION }}-macos-arm
          path: python-${{ env.PYTHON_VERSION }}-macos-arm.tar.gz