name: Build Python Windows (Clang)

on:
  push:
    branches: [ run-actions, main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

env:
  PYTHON_VERSION: 3.10.18

jobs:
  build-python-windows-clang:
    runs-on: windows-2022

    steps:
      - name: Install dependencies
        uses: microsoft/setup-msbuild@v1.3

      - name: Download Python source
        run: |
          curl -L -o Python-${{ env.PYTHON_VERSION }}.tgz https://www.python.org/ftp/python/${{ env.PYTHON_VERSION }}/Python-${{ env.PYTHON_VERSION }}.tgz
          tar -xf Python-${{ env.PYTHON_VERSION }}.tgz
        shell: bash

      - name: Build with Clang
        run: |
          cd Python-${{ env.PYTHON_VERSION }}/PCbuild
          build.bat -p x64 -t Build -e -d --use-clang
        shell: cmd

      - name: Package output
        run: |
          mkdir -p python-${{ env.PYTHON_VERSION }}-windows
          cp -r Python-${{ env.PYTHON_VERSION }}/PCbuild/amd64/* python-${{ env.PYTHON_VERSION }}-windows/
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-${{ env.PYTHON_VERSION }}-windows
          path: python-${{ env.PYTHON_VERSION }}-windows