name: Build Python Windows (PCbuild)

on:
  push:
    branches: [ run-actions, main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

env:
  PYTHON_VERSION: "3.13"
  PYTHON_VERSION_FULL: "3.13.6"

jobs:
  build-python-windows-pcbuild:
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: python/cpython
          ref: ${{ env.PYTHON_VERSION }}

      - name: Wix 3.14
        run: |
          curl -o wix314.exe https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314.exe
          ./wix314.exe /quiet /norestart
        shell: bash

      - name: Build
        continue-on-error: true
        run: ./Tools/msi/buildrelease.bat -x64 -D -o packaged-windows

      - name: List externals
        run: dir externals

      - name: List PCbuild/amd64
        run: dir PCbuild/amd64

      - name: Ensure pip is installed in built Python
        run: ./PCbuild/amd64/python.exe -m ensurepip --upgrade

      - name: Upgrade Sphinx
        run: ./PCbuild/amd64/python.exe -m pip install "sphinx<8.0"

      - name: Gen Docs
        run: |
          ./Doc/make.bat html
          ./Doc/make.bat htmlhelp

      - name: Build
        run: ./Tools/msi/buildrelease.bat -x64 -D -o packaged-windows
        
      - name: list and move to windows-amd64.exe
        run: |
          cd packaged-windows
          ls -lah .
          mv amd64/python-${{ env.PYTHON_VERSION_FULL }}-amd64.exe amd64/python-${{ env.PYTHON_VERSION_FULL }}-windows-amd64.exe
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-${{ env.PYTHON_VERSION_FULL }}-amd64
          path: packaged-windows/amd64/python-${{ env.PYTHON_VERSION_FULL }}-windows-amd64.exe