name: Build Python Windows (Clang)

on:
  push:
    branches: [ run-actions, main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

env:
  PYTHON_VERSION: 3.10.18

jobs:
  build-python-windows-clang:
    runs-on: windows-2025

    steps:

      - name: Download Python source
        run: |
          curl -L -# -o Python-${{ env.PYTHON_VERSION }}.tgz \
            https://www.python.org/ftp/python/${{ env.PYTHON_VERSION }}/Python-${{ env.PYTHON_VERSION }}.tgz
        shell: bash

      - name: Extract source
        run: |
          tar -xf Python-${{ env.PYTHON_VERSION }}.tgz -C .
        shell: bash

      - name: Set up Clang toolchain
        run: |
          echo "CC=clang" >> $GITHUB_ENV
          echo "AR=llvm-ar" >> $GITHUB_ENV
          echo "RANLIB=llvm-ranlib" >> $GITHUB_ENV
          echo "STRIP=llvm-strip" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          echo "LD=lld-link" >> $GITHUB_ENV
        shell: bash

      - name: Configure Python for Windows (clang)
        working-directory: python-src
        run: |
          ./configure \
            --prefix=$GITHUB_WORKSPACE/python-${{ env.PYTHON_VERSION }}-windows \
            --enable-optimizations \
            --without-ensurepip
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-${{ env.PYTHON_VERSION }}-windows
          path: python-${{ env.PYTHON_VERSION }}-windows