name: Build Python Windows (PCbuild)

on:
  push:
    branches: [ run-actions, main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

env:
  PYTHON_VERSION: "3.10"

jobs:
  build-python-windows-pcbuild:
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: python/cpython
          ref: ${{ env.PYTHON_VERSION }}

      - name: Wix 3.14
        run: |
          curl -o wix314.exe https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314.exe
          ./wix314.exe /quiet /norestart
        shell: bash

      - name: Build
        continue-on-error: true
        run: ./Tools/msi/buildrelease.bat -x64 -D -o packaged-windows

      - name: List externals
        run: dir externals

      - name: List externals/pythonx86
        run: dir externals/pythonx86

      - name: List externals/pythonx86/tools
        run: dir externals/pythonx86/tools

      - name: Upgrade Sphinx
        run: ./externals/pythonx86/tools/python.exe -m pip install "sphinx<8.0"

      - name: Gen Docs
        run: ./Doc/make.bat htmlhelp

      - name: Build
        run: ./Tools/msi/buildrelease.bat -x64 -D -o packaged-windows
        
      - name: list
        working-directory: C:/cpython
        run: ls packaged-windows

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-${{ env.PYTHON_VERSION }}-windows
          path: C:/cpython