name: Build Python Windows (Clang)

on:
  push:
    branches: [ run-actions, main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

env:
  PYTHON_VERSION: 3.10

jobs:
  build-python-windows-clang:
    runs-on: windows-2022

    steps:

      - name: Build with Clang
        run: |
          git clone --branch ${{ env.PYTHON_VERSION }} --depth 1 https://github.com/python/cpython.git .
          call Tools/msi/buildrelease.bat -x64 -D -o packaged-windows
          dir packaged-windows
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-${{ env.PYTHON_VERSION }}-windows
          path: packaged-windows