name: Build Python
on:
  push:
    branches:
      - run-actions
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write

env:
  PYTHON_VERSION: 3.13.5

jobs:
  configure-build-and-package-python-ubuntu:
    runs-on: windows-2025
    steps:
      - name: Download python source
        run: |
          curl -L -# -o Python-${{ env.PYTHON_VERSION }}.tgz \
            https://www.python.org/ftp/python/${{ env.PYTHON_VERSION }}/Python-${{ env.PYTHON_VERSION }}.tgz
        shell: bash

      - name: Extract tar.gz
        run: |
          tar -xf Python-${{ env.PYTHON_VERSION }}.tgz
          mv Python-${{ env.PYTHON_VERSION }}/* .

      - name: Configure python
        run: |
          ./configure --prefix=C:\\python-${{ env.PYTHON_VERSION }}-windows --enable-optimizations

      - name: Build python
        run: |
          make -j2

      - name: Install python
        run: |
          sudo make install

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-${{ env.PYTHON_VERSION }}-windows
          path: C:\\python-${{ env.PYTHON_VERSION }}-windows