name: Build Python Windows (PCbuild)

on:
  push:
    branches: [ run-actions, main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

env:
  PYTHON_VERSION: "3.10"

jobs:
  build-python-windows-pcbuild:
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: python/cpython
          ref: ${{ env.PYTHON_VERSION }}

      - name: Wix 3.14
        run: |
          wget https://objects.githubusercontent.com/github-production-release-asset-2e65be/17723789/5d9b40ab-3e89-4de1-a5d9-1699259020fa?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20250704%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250704T191740Z&X-Amz-Expires=1800&X-Amz-Signature=bfc4462b808bcf4afb12b69ea1c54e6cfb5e5fc1a7caa9557819df2817a31a22&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dwix314.exe&response-content-type=application%2Foctet-stream
          wix314.exe /quiet /norestart

      - name: Build
        continue-on-error: true
        run: ./Tools/msi/buildrelease.bat -x64 -D -o packaged-windows

      - name: List externals
        run: dir externals

      - name: List externals/pythonx86
        run: dir externals/pythonx86

      - name: List externals/pythonx86/tools
        run: dir externals/pythonx86/tools

      - name: Upgrade Sphinx
        run: ./externals/pythonx86/tools/python.exe -m pip install "sphinx<8.0"

      - name: Gen Docs
        run: ./Doc/make.bat htmlhelp

      - name: Build
        run: ./Tools/msi/buildrelease.bat -x64 -D -o packaged-windows
        
      - name: list
        working-directory: C:/cpython
        run: ls packaged-windows

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-${{ env.PYTHON_VERSION }}-windows
          path: C:/cpython